name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello and welcome to this repository! Thans for creating your first issue here! ~ Jonas"
        pr-message: "Hello and welcome to this repository! Thans for creating your first PR here! ~ Jonas"
